stages:
  - before_script
  - build
  - code_quality
  - after_script

image: teracy/angular-cli

before_script:

build:
  stage: build
  script: ng build --prod

code_quality:
  stage: code_quality
  script: /home/sonarqube/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=$SONAR_KEY -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN

after_script:
  - echo "End CI"
